Source as s3 bucket
detailnet/blitline pull request #2
Opened 2017-04-22 07:47 UTC by curzio-della-santa

2017-04-22 07:49 UTC, curzio-della-santa commented
![2017-04-22 09_42_46-blitline examples web01 detailnet me_job-submit php](https://cloud.githubusercontent.com/assets/7221909/25302547/e43b73c6-2740-11e7-9109-41158d2cba75.png)


![2017-04-22 09_42_57-blitline examples web01 detailnet me_job-info php_job_id 9srokkvodcoobbxxd8icwqg](https://cloud.githubusercontent.com/assets/7221909/25302561/eb3ff732-2740-11e7-9d7b-0e68313dfe5f.png)


![2017-04-22 09_42_22-blitline _ saas services landing](https://cloud.githubusercontent.com/assets/7221909/25302566/f4104c72-2740-11e7-9cc1-eb724979c427.png)

2017-04-24 15:36 UTC, ivan-wolf requested changes
@curzio-della-santa, please have a look.

2017-04-24 15:36 UTC, ivan-wolf commented on examples/config.php.dist
> +    //'s3file' => 'mountains.tif',
Does it make sense to configure a file here?

And please clean it up.

2017-04-24 15:36 UTC, ivan-wolf commented on examples/job-submit.php
> +            'key' => $getConfig('s3prefix') . '/' . $getConfig('s3file'),
Read file/path from URL param?

2017-04-24 15:36 UTC, ivan-wolf commented on examples/job-submit.php
> +                        'key' => $getConfig('s3prefix') . '/' . $imageName . '-' . $imageSize . '_blitline.jpg',
Extract prefix from given file/path.

2017-04-24 15:36 UTC, ivan-wolf commented on src/Detail/Blitline/Client/ServiceDescription/Blitline.php
> +                    'description' => 'The S3 location of the image you wish to process',
Is it an undocumented Blitline feature to pass an array? The documentation (http://www.blitline.com/docs/api) does not mention it.

2017-04-24 15:36 UTC, ivan-wolf commented on src/Detail/Blitline/Job/Definition/JobDefinition.php
> +    public function setSource(array $src)
Shouldn't we use an object for representation of a source?

2017-04-25 10:16 UTC, curzio-della-santa commented on src/Detail/Blitline/Client/ServiceDescription/Blitline.php
> +                    'description' => 'The S3 location of the image you wish to process',
yes is undocumented, only an example is given.

Blitline Example Jobs (http://docs.blitline.com/articles/examples.html)
- Using the permissions you’ve given Blitline for sources:	By default, Blitline assumes a source is public. If you instead want to have Blitline read OUT of your private bucket, you will need to change how the “src” is described. This is an example of using an “s3” source bucket and key

https://www.blitline.com/v3/home/gist?gist_id=3492389

2017-04-25 10:36 UTC, curzio-della-santa commented on src/Detail/Blitline/Job/Definition/JobDefinition.php
> +    public function setSource(array $src)
creating SourceInterface

2017-04-25 13:50 UTC, curzio-della-santa commented
http://blitline.examples.web01.detailnet.me/job-submit.php?image_url=https%3A%2F%2Fs3-eu-west-1.amazonaws.com%2Fcurzio-della-santa%2Ftest-files%2FDesert.jpg

http://blitline.examples.web01.detailnet.me/job-submit-s3.php?image_key=test-files%2FDesert.jpg

![processing_with_different_sources](https://cloud.githubusercontent.com/assets/7221909/25388664/bc356b8a-29ce-11e7-93cd-1e96c62c3c34.png)

2017-04-25 17:09 UTC, merged